### ISSUE TITLE
Identity

### ISSUE THREAD

**Issue by sieben07** [limetext/limetext.github.io#11]
The Website needs an Identity.
- [x] Favicon 
- [ ] Branding
- [ ] ???
- [x] Logo
- [ ] Colors

Open for suggestions and
everything should be usable for the text-editor.

**Comment by Shaunakde** [comment]
I could try to produce some branding images when I get home. Il give it a shot and post here. Should be fun.

**Comment by mmhyamin** [comment]
Hello everyone

Why don't you guys ask open source community volunteers to design a couple of elegant and modern logo for lime project and let the community vote for the final logo. It's effective and you will get the best output. From my point of view, most of the open source project's back-end is great but the front-end, logo and site from :( :( :( ~ 1999.

I am user of Sublime Text. From Twitter I found your project. As I am an open source fan I appreciate your project. As a user it's my open thought to you guys.

Cheers and Keep Rocking
Yamin
