### ISSUE TITLE
Home Page Design

### ISSUE THREAD

**Issue by mmhyamin** [limetext/limetext.github.io#44]
![screenshot from 2016-04-04 02-42-41](https://cloud.githubusercontent.com/assets/5278142/14234836/1c9f46bc-fa0f-11e5-9849-3585edaca3b7.png)

Hello
I have designed a homepage for lime text though I am not a designer. Let me know your feedback.
Thanks
##

**Comment by zoli** [comment]
I think it's better than the correct page, Thanks.

**Comment by erbridge** [comment]
Looks good to me, too. Feel free to submit a PR.

**Comment by jacobbearden** [comment]
Recently stumbled upon this, mind if I take a crack at it?

// @zoli @erbridge

**Comment by erbridge** [comment]
Please do.

**Comment by mmhyamin** [comment]
@jacobbearden Thanks. I coded the homepage but could not complete the other pages. Sorry I totally forgot about this. I will submit my PR after my exam. Thanks again for commenting.

**Comment by erbridge** [comment]
Merged in #46.

**Comment by nikhildascl** [comment]
Do we have the blog active? Shall we use medium blog?
