### ISSUE TITLE
Domain is gone, maybe don't redirect to limetext.org?

### ISSUE THREAD

**Issue by Giancarlos** [limetext/limetext.github.io#48]
At least this way the website is still up and available to view.

**Comment by zoli** [comment]
Yes we should let limetext.github.io come up.

**Comment by erbridge** [comment]
Done.

**Comment by darkmorpher** [comment]
@erbridge someone needs to update the old link on
https://github.com/limetext/lime  page
to point to `http://limetext.gtihub.io`
